[package]
name = "wrash"
version = "0.1.0"
authors = ["joshmeranda <joshmeranda@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
directories = "4.0"
regex = "1"
shlex = "1.1"
xdg = "2.4"
